version: "3"
volumes:
  home:
services:
  dev:
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: "."
      # Adjust the build args to reflect your local setup
      args:
        HOME: /home/me
        USER: me
        UID: 501
        GROUP: me
        GID: 501
    hostname: wiki-dev
    environment:
      # Adjust to reflect your own timezone
      - TZ=Europe/Berlin
    volumes:
      - home:/home
      # Adjust directories and user to reflect above changes to build args
      - ~/.ssh:/home/me/.ssh/
      - ..:/home/me/java-data
    working_dir: /home/me/java-data
    user: me
    ports:
      - "1313:1313"
